project:
  type: website
  output-dir: docs

website:
  title: "Maude Ceruso - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu: 
          - href: labs/lab0/lab0_Ceruso.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/your_file_name.qmd
            text: "Lab 1: Census Data Exploration"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
